// Placeholder lists - to be replaced with actual word lists
export const BASIC_WORD_LIST = [
 'maison', 'voiture', 'chat', 'chien', 'ordinateur', 'table', 'livre', 'école', 'travail', 'famille',
  'jardin', 'soleil', 'lune', 'étoile', 'musique', 'danse', 'peinture', 'cuisine', 'voyage', 'montagne',
  'rivière', 'forêt', 'plage', 'océan', 'ville', 'village', 'route', 'train', 'avion', 'bateau',
  'fleur', 'arbre', 'oiseau', 'poisson', 'papillon', 'téléphone', 'fenêtre', 'porte', 'mur', 'toit',
  'ami', 'amour', 'fête', 'noël', 'école', 'université', 'classe', 'étudiant', 'professeur', 'livre',
  'papier', 'crayon', 'stylo', 'lettre', 'mot', 'phrase', 'histoire', 'photo', 'film', 'musée',
  'magasin', 'supermarché', 'restaurant', 'café', 'boulangerie', 'chocolat', 'pain', 'eau', 'vin', 'fromage',
  'viande', 'poisson', 'légume', 'fruit', 'soupe', 'salade', 'plat', 'dessert', 'gâteau', 'glace',
  'saison', 'été', 'hiver', 'printemps', 'automne', 'jour', 'nuit', 'matin', 'soir', 'minuit',
  'semaine', 'mois', 'année', 'heure', 'minute', 'seconde', 'temps', 'énergie', 'climatisation', 'chauffage',
  'santé', 'médecin', 'hôpital', 'soin', 'maladie', 'remède', 'pilule', 'médecine', 'chirurgie', 'urgence',
  'pouvoir', 'liberté', 'égalité', 'justice', 'loi', 'armée', 'police', 'sécurité', 'violence', 'crime',
  'politique', 'élection', 'parti', 'gouvernement', 'président', 'maire', 'député', 'sénateur', 'conseil', 'loi',
  'monnaie', 'argent', 'bourse', 'banque', 'économie', 'commerce', 'marché', 'travail', 'emploi', 'carrière',
  'salaire', 'impôt', 'taxe', 'retraite', 'sécurité', 'sociale', 'assurance', 'assurance-vie', 'pension', 'chômage',
  'tourisme', 'hôtel', 'voyage', 'vacances', 'plage', 'montagne', 'campagne', 'pays', 'région', 'ville',
  'quartier', 'zone', 'centre', 'banlieue', 'agglomération', 'immeuble', 'appartement', 'maison', 'résidence', 'chambre',
  'salon', 'cuisine', 'salle', 'salle de bain', 'toilette', 'jardin', 'terrasse', 'balcon', 'cave', 'grenier',
  'meuble', 'canapé', 'table', 'chaise', 'lit', 'armoire', 'étagère', 'tapis', 'rideau', 'lampe',
  'coussin', 'miroir', 'peinture', 'tableau', 'sculpture', 'photo', 'objet', 'décoration', 'accessoire', 'outil',
  'bâtiment', 'construction', 'rue', 'avenue', 'place', 'carrefour', 'croisement', 'intersection', 'pont', 'tunnel'
];

export const ADVANCED_WORD_LIST = [
  'coussin', 'miroir', 'peinture', 'tableau', 'sculpture', 'photo', 'objet', 'décoration', 'accessoire', 'outil',
  'bâtiment', 'construction', 'rue', 'avenue', 'place', 'carrefour', 'croisement', 'intersection', 'pont', 'tunnel',
  'vélo', 'moto', 'véhicule', 'mécanicien', 'conducteur', 'passager', 'panne', 'réparation', 'station', 'parking',
  'voiture', 'route', 'autoroute', 'panneau', 'signalisation', 'feu', 'feu de signalisation', 'carte', 'plan', 'gps',
  'métro', 'bus', 'tram', 'taxi', 'train', 'station', 'arrêt', 'voyageur', 'billet', 'portefeuille',
  'sac', 'valise', 'passeport', 'ticket', 'réservation', 'compagnie', 'aéroport', 'avion', 'terminal',
  'vol', 'annulation', 'embarquement', 'repas', 'bagage', 'main', 'poignet', 'doigt', 'bras',
  'épaule', 'cou', 'tête', 'oreille', 'yeux', 'nez', 'bouche', 'langue', 'dent', 'gorge',
  'dos', 'estomac', 'ventre', 'genou', 'pied', 'cheville', 'orteil', 'sang', 'sueur',
  'respiration', 'mouvement', 'muscle', 'os', 'peau', 'cheveux', 'maquillage', 'coiffure', 'frange', 'barbe',
  'moustache', 'lèvre', 'cicatrice', 'blessure', 'pansement', 'douleur', 'fièvre', 'mal de tête', 'rendez-vous',
  'médecin', 'hôpital', 'urgences', 'pharmacie', 'médecin traitant', 'consultation', 'diagnostic', 'analyse', 'radiographie', 'chirurgie',
  'opération', 'rééducation', 'réponse', 'question', 'information', 'réponse', 'conseil', 'avis', 'suggestion',
  'proposition', 'choix', 'décision', 'solution', 'problème', 'difficulté', 'conflit', 'dispute', 'accord',
  'compromis', 'discussion', 'négociation', 'accord', 'entente', 'mécontentement', 'réclamation', 'réponse', 'demande',
  'attente', 'résultat', 'réussite', 'échec', 'objectif', 'but', 'plan', 'projet', 'exécution',
  'contrat', 'engagement', 'obligation', 'responsabilité', 'droit', 'loi', 'règle', 'norme', 'moral',
  'éthique', 'valeur', 'principe', 'culture', 'tradition', 'coutume', 'religion', 'foi', 'prière',
  'saison', 'vacances', 'célébration', 'événement', 'réunion', 'conférence', 'symposium', 'congrès', 'exposition', 'spectacle',
  'festival', 'concert', 'théâtre', 'cinéma', 'musée', 'restaurant', 'bar', 'pub', 'club',
  'magasin', 'supermarché', 'boulangerie', 'café', 'restaurant', 'marché', 'vendeur', 'client', 'produit', 'prix',
  'argent', 'monnaie', 'portefeuille', 'carte', 'debit', 'crédit', 'banque', 'compte', 'transfert', 'épargne',
  'investissement', 'valeur', 'actions', 'bourse', 'marché financier', 'emprunt', 'dette', 'interêt', 'loyer',
  'hypothèque', 'assurance', 'produit d\'assurance', 'réclamation', 'dommages', 'sinistre', 'vol', 'incendie', 'accident', 'dégât',
  'responsabilité', 'droit', 'contrat', 'garantie', 'assurance-vie', 'prêt', 'crédit', 'bail', 'location',
  'propriétaire', 'locataire', 'sous-louer', 'contrat de travail', 'employé', 'employeur', 'salarié', 'contrat à durée déterminée', 'CDI',
  'CDD', 'interim', 'stage', 'formation', 'recrutement', 'postuler', 'entretien', 'démission', 'licenciement', 'chômage',
  'pension', 'retraite', 'allocations', 'avantages', 'congés', 'vacances', 'repos', 'jour férié', 'week-end',
  'présentation', 'entretien', 'sélection', 'test', 'examen', 'évaluation', 'compétence', 'qualification', 'expérience', 'CV',
  'lettre de motivation', 'offre d\'emploi', 'candidature', 'embauche', 'équipe', 'collègue', 'travail d\'équipe', 'responsabilité',
  'gestion', 'chef', 'manager', 'directeur', 'supérieur', 'réunion', 'réponse', 'contrat', 'objectif', 'projet',
  'planification', 'organisation', 'priorité', 'délai', 'suivi', 'contrôle', 'plan', 'échéance', 'budget',
  'facture', 'comptabilité', 'compte', 'compte bancaire', 'transaction', 'taxe', 'TVA', 'impôt', 'droit de douane', 'douane',
  'commerce', 'affaires', 'entreprise', 'industrie', 'secteur', 'marché', 'publicité', 'marketing', 'campagne', 'vente',
  'produit', 'service', 'client', 'fidélité', 'satisfaction', 'retour', 'évaluation', 'réputation', 'avis',
  'satisfaction', 'économie', 'croissance', 'chiffre d\'affaires', 'profit', 'perte', 'rentabilité', 'entrepreneur', 'start-up',
  'marché cible', 'positionnement', 'concurrence', 'part de marché', 'stratégie', 'analyse', 'risque', 'innovation', 'technologie',
  'développement', 'numérique', 'digital', 'web', 'réseaux sociaux', 'publicité en ligne', 'SEO', 'SEM', 'référencement',
  'application', 'site web', 'e-commerce', 'boutique en ligne', 'site internet', 'blog', 'vlog', 'créateur', 'influenceur',
  'vidéo', 'photo', 'musique', 'créativité', 'design', 'graphisme', 'créateur de contenu', 'start-up', 'incubateur',
  'accélérateur', 'programme d\'incubation', 'investissement', 'financement', 'capital-risque', 'crowdfunding', 'levée de fonds', 'entrepreneur',
  'portefeuille', 'investisseur', 'actionnaire', 'action', 'bourse', 'marché financier', 'dividende', 'rentabilité', 'portefeuille d\'actions',
  'bon de souscription', 'obligation', 'marché obligataire', 'régulation', 'législation', 'conformité', 'protection des données', 'confidentialité', 'RGPD',
  'droit d\'auteur', 'propriété intellectuelle', 'brevet', 'marque', 'licence', 'contrat de licence', 'patent', 'marque déposée', 'copyright',
  'invention', 'innovation', 'création', 'droit d\'utilisation', 'société', 'partenariat', 'fusion', 'acquisition', 'joint-venture',
   'capital', 'trésorerie', 'actif', 'passif', 'bilan', 'profit', 'perte', 'trésorerie', 'solvabilité', 'rentabilité',
  'liquidité', 'créance', 'dette', 'engagement', 'banque', 'crédit', 'prêt', 'solde', 'compte bancaire',
  'monnaie', 'billet', 'pièce', 'change', 'échange', 'taux de change', 'devise', 'international', 'globalisation', 'commerce international',
  'logistique', 'transports', 'douane', 'import-export', 'contrôle', 'qualité', 'produit', 'fabrication', 'production',
  'assemblage', 'prototypes', 'technologie', 'recherche', 'développement', 'innovation', 'apprentissage', 'formation', 'enseignement',
  'éducation', 'diplôme', 'université', 'école', 'faculté', 'classe', 'enseignant', 'étudiant', 'école primaire',
  'collège', 'lycée', 'programme', 'cursus', 'scolarité', 'bourse', 'apprentissage', 'stage', 'recherche',
  'mémoire', 'thèse', 'soutenance', 'diplôme', 'certificat', 'études supérieures', 'licence', 'master', 'doctorat',
  'évaluation', 'notation', 'examen', 'test', 'dossier', 'remise de diplôme', 'inscription', 'inscrire', 'abonnement', 'cours',
  'emploi', 'stage', 'formation', 'recrutement', 'entretien', 'CV', 'lettre de motivation', 'recommandation', 'référence'
];